version: '3'
services:
  gateway-api:
    image: python:3.9
    container_name: gateway-api
    working_dir: /app
    environment:
      USERS_URL: https://back-users-merok23.cloud.okteto.net
      ADMINS_URL: https://admins-45ja.onrender.com/api/v1
      SNAPMSG_URL: https://postsback.onrender.com
      METRICS_URL: https://snapmsgs-metrics.onrender.com
    ports:
      - "8080:8080"
    command: bash -c "pip install --no-cache-dir -r requirements.txt && uvicorn control.controller:app --host 0.0.0.0 --port 8080"
    volumes:
      - .:/app
