apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-api-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gateway-api
  template:
    metadata:
      labels:
        app: gateway-api
    spec:
      containers:
        - name: gateway-api
          image: merok23/gateway-api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: USERS_URL
              value: https://back-users-merok23.cloud.okteto.net
            - name: ADMINS_URL
              value: https://admins-backend-merok23.cloud.okteto.net/api/v1
            - name: SNAPMSG_URL
              value: https://postsback.onrender.com
            - name: METRICS_URL
              value: 
