
name: Docker Build and Deploy

on:
  push:
    # branches:
    #   - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: merok23/gateway-api:latest
  k8s:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up kubectl
        uses: azure/k8s-set-context@v1
        with:
          kubeconfig: ${{ secrets.KUBE_CONFIG_DATA }}
      
      - name: Set up Okteto
        uses: okteto/setup-okteto@v1
        with:
          token: ${{ secrets.OKTETO_TOKEN }}
          namespace: ${{ secrets.OKTETO_NAMESPACE }}
      - name: Deploy to Okteto
        uses: okteto/deploy-action@v1
        with:
          manifest: k8s-deployment.yaml
          image: merok23/gateway-api:latest
          registry-secret: dockerhub
          force-pull: true
          wait: true
          timeout: 1200
          namespace: ${{ secrets.OKTETO_NAMESPACE }}
          